### ISSUE TITLE
how to get OSDAR23 Dataset

### ISSUE THREAD

**Issue by liuweixue001** [egemenkopuz/temporal-bevfusion#9]
hello, i want know how to get OSDAR23 Dataset, thanks

**Comment by egemenkopuz** [comment]
Here is the link: https://data.fid-move.de/dataset/osdar23
You can individually download the sequences.

**Comment by liuweixue001** [comment]
> Here is the link: https://data.fid-move.de/dataset/osdar23 You can individually download the sequences.

thank you
